In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('tickets.csv')

In [3]:
data.head()

,ticket_id,created_at,customer_id,customer_segment,channel,product_area,issue_type,priority,status,sla_plan,initial_message,agent_first_reply,resolution_summary,resolution_time_hours,reopened,customer_sentiment,csat_score,has_attachment,platform,region
0,TCKT_000001,2024-01-31T05:14:27,CUST_00861,individual,email,data_export,account_access,low,resolved,standard,I cannot log in; the system says my password i...,Sorry to hear you're having trouble accessing ...,Reset account credentials and confirmed succes...,36.53,0,very_negative,1,0,android,EU
1,TCKT_000002,2024-10-20T06:15:49,CUST_00770,individual,in_app,billing,security_concern,medium,closed_no_action,standard,I noticed a suspicious login on my account.,We take security very seriously. Our team is r...,Ticket closed without further action after no ...,238.32,0,neutral,3,0,web,NaN
2,TCKT_000003,2024-06-18T21:35:54,CUST_02559,small_business,chat,api_integration,bug,low,in_progress,standard,The api integration feature is not saving my c...,Thanks for reporting this bug. We will look in...,NaN,NaN,0,neutral,3,0,android,MEA
3,TCKT_000004,2025-12-25T15:59:52,CUST_03557,education,chat,analytics_dashboard,account_access,medium,in_progress,standard,I cannot log in; the system says my password i...,Sorry to hear you're having trouble accessing ...,NaN,NaN,0,positive,5,1,android,LATAM
4,TCKT_000005,2023-08-27T16:08:33,CUST_09556,enterprise,phone_transcript,login_auth,billing_problem,low,resolved,gold,My invoice amount is incorrect compared to the...,Thanks for reaching out about the billing issu...,Adjusted the invoice and issued a refund where...,61.32,0,very_negative,2,0,web,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ticket_id              100000 non-null  object
 1   created_at             100000 non-null  object
 2   customer_id            100000 non-null  object
 3   customer_segment       100000 non-null  object
 4   channel                100000 non-null  object
 5   product_area           100000 non-null  object
 6   issue_type             100000 non-null  object
 7   priority               100000 non-null  object
 8   status                 100000 non-null  object
 9   sla_plan               100000 non-null  object
 10  initial_message        100000 non-null  object
 11  agent_first_reply      100000 non-null  object
 12  resolution_summary     60113 non-null   object
 13  resolution_time_hours  60113 non-null   float64
 14  reopened               100000 non-null  int64
 15  customer_sentiment     100000 non-null  object
 16  csat_score             100000 non-null  int64
 17  has_attachment         100000 non-null  int64
 18  platform               100000 non-null  object
 19  region                 80003 non-null   object
dtypes: float64(1), int64(3), object(16)
memory usage: 15.3+ MB

In [6]:
data.isnull().sum()

ticket_id                    0
created_at                   0
customer_id                  0
customer_segment             0
channel                      0
product_area                 0
issue_type                   0
priority                     0
status                       0
sla_plan                     0
initial_message              0
agent_first_reply            0
resolution_summary       39887
resolution_time_hours    39887
reopened                     0
customer_sentiment           0
csat_score                   0
has_attachment               0
platform                     0
region                   19997
dtype: int64

In [8]:
data[data.duplicated(subset=['ticket_id'], keep=False)]

Empty DataFrame
Columns: [ticket_id, created_at, customer_id, customer_segment, channel, product_area, issue_type, priority, status, sla_plan, initial_message, agent_first_reply, resolution_summary, resolution_time_hours, reopened, customer_sentiment, csat_score, has_attachment, platform, region]
Index: []

In [9]:
data['created_at']=pd.to_datetime(data['created_at'])

In [11]:
data['year']=data['created_at'].dt.year
data['month']=data['created_at'].dt.month
data['day']=data['created_at'].dt.day
data['hour']=data['created_at'].dt.hour

In [12]:
data.head(5)

,ticket_id,created_at,customer_id,customer_segment,channel,product_area,issue_type,priority,status,sla_plan,...,reopened,customer_sentiment,csat_score,has_attachment,platform,region,year,month,day,hour
0,TCKT_000001,2024-01-31 05:14:27,CUST_00861,individual,email,data_export,account_access,low,resolved,standard,...,0,very_negative,1,0,android,EU,2024,1,31,5
1,TCKT_000002,2024-10-20 06:15:49,CUST_00770,individual,in_app,billing,security_concern,medium,closed_no_action,standard,...,0,neutral,3,0,web,NaN,2024,10,20,6
2,TCKT_000003,2024-06-18 21:35:54,CUST_02559,small_business,chat,api_integration,bug,low,in_progress,standard,...,0,neutral,3,0,android,MEA,2024,6,18,21
3,TCKT_000004,2025-12-25 15:59:52,CUST_03557,education,chat,analytics_dashboard,account_access,medium,in_progress,standard,...,0,positive,5,1,android,LATAM,2025,12,25,15
4,TCKT_000005,2023-08-27 16:08:33,CUST_09556,enterprise,phone_transcript,login_auth,billing_problem,low,resolved,gold,...,0,very_negative,2,0,web,NaN,2023,8,27,16

In [14]:
data.region.unique()

array(['EU', nan, 'MEA', 'LATAM', 'APAC'], dtype=object)

In [15]:
data['region']=data['region'].fillna('unknown')

In [16]:
data.head()

,ticket_id,created_at,customer_id,customer_segment,channel,product_area,issue_type,priority,status,sla_plan,...,reopened,customer_sentiment,csat_score,has_attachment,platform,region,year,month,day,hour
0,TCKT_000001,2024-01-31 05:14:27,CUST_00861,individual,email,data_export,account_access,low,resolved,standard,...,0,very_negative,1,0,android,EU,2024,1,31,5
1,TCKT_000002,2024-10-20 06:15:49,CUST_00770,individual,in_app,billing,security_concern,medium,closed_no_action,standard,...,0,neutral,3,0,web,unknown,2024,10,20,6
2,TCKT_000003,2024-06-18 21:35:54,CUST_02559,small_business,chat,api_integration,bug,low,in_progress,standard,...,0,neutral,3,0,android,MEA,2024,6,18,21
3,TCKT_000004,2025-12-25 15:59:52,CUST_03557,education,chat,analytics_dashboard,account_access,medium,in_progress,standard,...,0,positive,5,1,android,LATAM,2025,12,25,15
4,TCKT_000005,2023-08-27 16:08:33,CUST_09556,enterprise,phone_transcript,login_auth,billing_problem,low,resolved,gold,...,0,very_negative,2,0,web,unknown,2023,8,27,16

In [18]:
print("Priority")
print(data['priority'].value_counts())

print("\nStatus")
print(data['status'].value_counts())

print("\nIssue Type")
print(data['issue_type'].value_counts())

Priority
priority
low       39735
medium    35313
high      19865
urgent     5087
Name: count, dtype: int64

Status
status
resolved            50131
in_progress         19783
on_hold             10165
closed_no_action     9982
open                 9939
Name: count, dtype: int64

Issue Type
issue_type
how_to              12739
account_access      12609
performance         12513
feature_request     12487
other               12463
security_concern    12458
billing_problem     12382
bug                 12349
Name: count, dtype: int64

In [19]:
print("\nProduct Area")
print(data['product_area'].value_counts())

print("\nCustomer Segment")
print(data['customer_segment'].value_counts())

print("\nChannel")
print(data['channel'].value_counts())

Product Area
product_area
mobile_app             14432
login_auth             14381
api_integration        14350
billing                14289
data_export            14262
analytics_dashboard    14187
notifications          14099
Name: count, dtype: int64

Customer Segment
customer_segment
small_business    20203
individual        20033
enterprise        20030
education         19958
non_profit        19776
Name: count, dtype: int64

Channel
channel
phone_transcript    20133
email               20088
in_app              19982
web_form            19965
chat                19832
Name: count, dtype: int64

In [20]:
print("\nSLA Plan")
print(data['sla_plan'].value_counts())

print("\nPlatform")
print(data['platform'].value_counts())

print("\nCustomer Sentiment")
print(data['customer_sentiment'].value_counts())

SLA Plan
sla_plan
standard    60066
gold        29875
platinum    10059
Name: count, dtype: int64

Platform
platform
api_client     20095
web            20025
desktop_app    20015
ios            20009
android        19856
Name: count, dtype: int64

Customer Sentiment
customer_sentiment
neutral          32634
negative         26015
very_negative    16437
positive         16242
very_positive     8672
Name: count, dtype: int64

In [21]:
data.status.unique()

array(['resolved', 'closed_no_action', 'in_progress', 'on_hold', 'open'],
      dtype=object)

In [ ]:
data..unique()

array(['individual', 'small_business', 'education', 'enterprise',
       'non_profit'], dtype=object)